'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NewsItem
    Public Property Id As Integer
    Public Property Category As String
    Public Property Organization As String
    Public Property Title As String
    Public Property LinkTitle As String
    Public Property Description As String
    Public Property DateCreated As Date
    Public Property DateModified As Date
    Public Property CreatedBy As String
    Public Property ModifiedBy As String
    Public Property DisplayItem As Boolean
    Public Property ArchiveDate As Nullable(Of Date)

End Class
